[build]
command = "npm run build"
publish = "build/client"

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames
[[headers]]
for = "/build/*"
[headers.values]
Cache-Control = "public, max-age=31560000, immutable"

[[headers]]
for = "/entry.worker.js"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
Service-Worker-Allowed = "/"

[[headers]]
for = "/manifest.json"
[headers.values]
Cache-Control = "public, max-age=600"
